export const LOGO = "https://cdn.cookielaw.org/logos/dd6b162f-1a32-456a-9cfe-897231c7763c/4345ea78-053c-46d2-b11e-09adaef973dc/Netflix_Logo_PMS.png"

export const USER_AVATAR = "https://wallpapers.com/images/high/netflix-profile-pictures-1000-x-1000-qo9h82134t9nv0j0.webp";

export const BG_LOGO = "https://assets.nflxext.com/ffe/siteui/vlv3/fc164b4b-f085-44ee-bb7f-ec7df8539eff/d23a1608-7d90-4da1-93d6-bae2fe60a69b/IN-en-20230814-popsignuptwoweeks-perspective_alpha_website_large.jpg"

export const API_OPTIONS = {
    method: 'GET',
    headers: {
      accept: 'application/json',
      Authorization: 'Bearer ' + process.env.REACT_APP_TMDB_KEY
    }
  };

export const IMG_CDN_URL = "https://image.tmdb.org/t/p/w500";

export const SUPPORTED_LANGUAGES = [
    { identifier: "english", name: "English" },
    { identifier: "afrikaans", name: "Afrikaans" },
    { identifier: "albanian", name: "Albanian" },
    { identifier: "amharic", name: "Amharic" },
    { identifier: "arabic", name: "Arabic" },
    { identifier: "azerbaijani", name: "Azerbaijani" },
    { identifier: "basque", name: "Basque" },
    { identifier: "belarusian", name: "Belarusian" },
    { identifier: "bengali", name: "Bengali" },
    { identifier: "bosnian", name: "Bosnian" },
    { identifier: "bulgarian", name: "Bulgarian" },
    { identifier: "catalan", name: "Catalan" },
    { identifier: "chinese", name: "Chinese" },
    { identifier: "corsican", name: "Corsican" },
    { identifier: "croatian", name: "Croatian" },
    { identifier: "czech", name: "Czech" },
    { identifier: "danish", name: "Danish" },
    { identifier: "dutch", name: "Dutch" },
    { identifier: "estonian", name: "Estonian" },
    { identifier: "fijian", name: "Fijian" },
    { identifier: "filipino", name: "Filipino" },
    { identifier: "finnish", name: "Finnish" },
    { identifier: "french", name: "French" },
    { identifier: "frisian", name: "Frisian" },
    { identifier: "galician", name: "Galician" },
    { identifier: "german", name: "German" },
    { identifier: "greek", name: "Greek" },
    { identifier: "gujarati", name: "Gujarati" },
    { identifier: "haitian", name: "Haitian Creole" },
    { identifier: "hawaiian", name: "Hawaiian" },
    { identifier: "hebrew", name: "Hebrew" },
    { identifier: "hindi", name: "Hindi" },
    { identifier: "hmong", name: "Hmong" },
    { identifier: "hungarian", name: "Hungarian" },
    { identifier: "icelandic", name: "Icelandic" },
    { identifier: "igbo", name: "Igbo" },
    { identifier: "indonesian", name: "Indonesian" },
    { identifier: "irish", name: "Irish" },
    { identifier: "italian", name: "Italian" },
    { identifier: "japanese", name: "Japanese" },
    { identifier: "javanese", name: "Javanese" },
    { identifier: "kannada", name: "Kannada" },
    { identifier: "korean", name: "Korean" },
    { identifier: "latvian", name: "Latvian" },
    { identifier: "lithuanian", name: "Lithuanian" },
    { identifier: "luxembourgish", name: "Luxembourgish" },
    { identifier: "malagasy", name: "Malagasy" },
    { identifier: "malayalam", name: "Malayalam" },
    { identifier: "maltese", name: "Maltese" },
    { identifier: "maori", name: "Maori" },
    { identifier: "marathi", name: "Marathi" },
    { identifier: "mongolian", name: "Mongolian" },
    { identifier: "nepalese", name: "Nepali" },
    { identifier: "norwegian", name: "Norwegian" },
    { identifier: "northern_sotho", name: "Northern Sotho" },
    { identifier: "occitan", name: "Occitan" },
    { identifier: "oromo", name: "Oromo" },
    { identifier: "persian", name: "Persian" },
    { identifier: "polish", name: "Polish" },
    { identifier: "portuguese", name: "Portuguese" },
    { identifier: "punjabi", name: "Punjabi" },
    { identifier: "romanian", name: "Romanian" },
    { identifier: "russian", name: "Russian" },
    { identifier: "samoan", name: "Samoan" },
    { identifier: "serbian", name: "Serbian" },
    { identifier: "sesotho", name: "Sesotho" },
    { identifier: "shona", name: "Shona" },
    { identifier: "sindhi", name: "Sindhi" },
    { identifier: "sinhala", name: "Sinhala" },
    { identifier: "slovak", name: "Slovak" },
    { identifier: "slovenian", name: "Slovenian" },
    { identifier: "somali", name: "Somali" },
    { identifier: "spanish", name: "Spanish" },
    { identifier: "swahili", name: "Swahili" },
    { identifier: "swedish", name: "Swedish" },
    { identifier: "tamil", name: "Tamil" },
    { identifier: "tatar", name: "Tatar" },
    { identifier: "telugu", name: "Telugu" },
    { identifier: "thai", name: "Thai" },
    { identifier: "tswana", name: "Tswana" },
    { identifier: "turkish", name: "Turkish" },
    { identifier: "turkmen", name: "Turkmen" },
    { identifier: "ukrainian", name: "Ukrainian" },
    { identifier: "urdu", name: "Urdu" },
    { identifier: "uyghur", name: "Uyghur" },
    { identifier: "vietnamese", name: "Vietnamese" },
    { identifier: "welsh", name: "Welsh" },
    { identifier: "xhosa", name: "Xhosa" },
    { identifier: "yoruba", name: "Yoruba" }
];

export const OPENAI_KEY = process.env.REACT_APP_OPENAI_KEY; // ✅ Correct way

